# Generated by Django 4.1.7 on 2023-02-18 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0002_alter_image_image"),
        ("accounts", "0002_useraccount_account_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounttier",
            name="get_original_file",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accounttier",
            name="thumbnail_sizes",
            field=models.ManyToManyField(blank=True, to="images.thumbnailsize"),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="account_tier",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="users", to="accounts.accounttier"
            ),
        ),
    ]
