# Generated by Django 4.1.7 on 2023-02-20 22:44

import ImageUploadApi.storage
from django.db import migrations, models
import django.db.models.deletion
import images.utils
import images.validators
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expiringlink",
            name="expiry_time",
        ),
        migrations.AddField(
            model_name="expiringlink",
            name="expires_in",
            field=models.IntegerField(default=0, validators=[images.validators.validate_expiration_time]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="expiringlink",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="expiringlink",
            name="image",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="expiring_link", to="images.image"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                storage=ImageUploadApi.storage.GoogleCloudMediaFileStorage,
                upload_to=images.utils.image_upload_path,
                validators=[images.validators.validate_image_extension],
            ),
        ),
    ]
