# Generated by Django 4.1.7 on 2023-02-18 22:28

from django.db import migrations, models

import images.utils
import images.validators
import ImageUploadApi.storage


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                storage=ImageUploadApi.storage.CustomImageStorage(),
                upload_to=images.utils.image_upload_path,
                validators=[images.validators.validate_image_extension],
            ),
        ),
    ]
