# Generated by Django 4.1.7 on 2023-02-19 21:53

from django.db import migrations, models
import django.db.models.deletion
import images.validators
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0002_alter_image_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expiringlink",
            name="expiry_time",
        ),
        migrations.AddField(
            model_name="expiringlink",
            name="expires_in",
            field=models.IntegerField(default=0, validators=[images.validators.validate_expiration_time]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="expiringlink",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="expiringlink",
            name="image",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="expiring_link", to="images.image"
            ),
        ),
    ]
