# Generated by Django 4.1.7 on 2023-02-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_remove_expiringlink_expiry_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiringlink',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
